version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: DatabaseDockerfile
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapeo del puerto de PostgreSQL

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"  # Puerto de la aplicación Spring Boot

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"  # Puerto del servidor web para la aplicación Angular
